### ISSUE TITLE
非常严重的卡顿问题

### ISSUE THREAD

**Issue by People-11** [xiaokaixuan/prevent-patch#1]
当安装了补丁后，我的手机出现了非常严重的卡顿问题，经过我一个晚上的研究（重刷系统x13），我发现当services.jar被替换后，系统只会使用没有odex化的services.jar（即使已经使用修复卡顿补丁创建了odex和vdex）这就造成了卡顿问题。所以现在的问题就是当services.jar被替换后系统只会用没有odex化的services.jar。

**Comment by xiaokaixuan** [comment]
你说的这个问题我也遇到过，但是在手机上用root运行fix_brevent.sh后，重下生成了odex和vdex就好了。
